---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx service
      command: service nginx stopped

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2 service
      command: service apache2 stopped

- hosts: database
  become: true
  tasks:
    - name: verify mysql service
      command: service mysql stopped
